apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 1.0.23
    helm:
      valuesObject:
        singleNamespace: true
        createAggregateRoles: false
        controller:
          persistence:
            archive: false
          clusterWorkflowTemplates:
            enabled: false
        workflow:
          serviceAccount:
            create: false
            name: eatbid-dataplane
          rbac:
            create: true
        server:
          enabled: false
        crds:
          install: true
          keep: true
          full: true
  destination:
    server: https://kubernetes.default.svc
    namespace: eatbid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
