apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: eatbid
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DATABASE_URL
              value: null
              valueFrom:
                secretKeyRef:
                  name: eatbid-database
                  key: DATABASE_URL
