apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - poll.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: db-schema
    namespace: eatbid
    files: [schema.sql]
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: eatbid-server
    newName: ghcr.io/lamyzm/eatbid-server
    newTag: e5a6564
  - name: eatbid-web
    newName: ghcr.io/lamyzm/eatbid-web
    newTag: e5a6564
