apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - poll.yaml
  - tunnel.yaml
  - serviceaccount.yaml
images:
  - name: eatbid-server
    newName: ghcr.io/lamyzm/eatbid-server
    newTag: e1abb82
  - name: eatbid-web
    newName: ghcr.io/lamyzm/eatbid-web
    newTag: e1abb82
